INSERT INTO CODE(ID,CODE_SIZE) VALUES(1,4);
INSERT INTO GAME(ID,CODE) VALUES (1,1);

INSERT INTO PEG VALUES(0,'PINK',1,NULL,0);
INSERT INTO PEG VALUES(1,'BLUE',1,NULL,1);
INSERT INTO PEG VALUES(2,'PURPLE',1,NULL,2);
INSERT INTO PEG VALUES(3,'SILVER',1,NULL,3);


INSERT INTO CODE(ID,CODE_SIZE) VALUES(2,4);
INSERT INTO GAME(ID,CODE) VALUES (2,2);

INSERT INTO PEG VALUES(4,'SILVER',2,NULL,0);
INSERT INTO PEG VALUES(5,'BLUE',2,NULL,1);
INSERT INTO PEG VALUES(6,'SILVER',2,NULL,2);
INSERT INTO PEG VALUES(7,'SILVER',2,NULL,3);





