INSERT INTO CODE(CODE_SIZE) VALUES(4);
INSERT INTO GAME(CODE) VALUES (1);

INSERT INTO PEG VALUES(0,'PINK',1,0);
INSERT INTO PEG VALUES(1,'BLUE',1,1);
INSERT INTO PEG VALUES(2,'PURPLE',1,2);
INSERT INTO PEG VALUES(3,'SILVER',1,3);


INSERT INTO CODE(CODE_SIZE) VALUES(4);
INSERT INTO GAME(CODE) VALUES (2);

INSERT INTO PEG VALUES(4,'SILVER',2,0);
INSERT INTO PEG VALUES(5,'BLUE',2,1);
INSERT INTO PEG VALUES(6,'SILVER',2,2);
INSERT INTO PEG VALUES(7,'SILVER',2,3);





